---
- name: Listen for Github Webhooks
  hosts: all
  sources:
    - name: Listen for webhook events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run playbook on a push event
      condition: event.headers['X-Github-Event'] == "push"
      action:
        run_playbook:
          name: hello-eda.yml
